# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wYgxsUshmzJL5rm_tURXD3Gr8MaUtA7N
"""

pip install chatterbot

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

bot = ChatBot(
    'Mi primer chat bot'
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    database_uri='sqlite:///basedatosconversacionl.sqlite3',
    logic_adapters=[
                    'chatterbot.logic.BestMach',
    ]

)

trainer = ListTrainer(ChatBot)

trainer.train([
     'hola como estas'
     'bien gracias'
     'me alegro mucho'
     'gracias'          
])

trainer.train([
               'hola como estas'
               'estoy genial'
               '¡que bien!'
               'Gracias'
])

while True:
  try:
    bot_input = bot.get_responde(input())
    print(bot_input)

    except (KeyboardInterrupt, E0FError, SystemExit):
      break